package com.dolby.dcinema.ws.smi.v1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.1
 * 2015-07-09T17:38:11.748+02:00
 * Generated source version: 3.1.1
 * 
 */
@WebService(targetNamespace = "http://www.dolby.com/dcinema/ws/smi/v1", name = "PlaybackControlService_v1_3")
@XmlSeeAlso({com.dolby.dcinema.ws.smi.v1_4.ObjectFactory.class, com.dolby.dcinema.ws.smi.v1_3.ObjectFactory.class, com.dolby.dcinema.ws.smi.v1.schemas.common.ObjectFactory.class, com.dolby.dcinema.ws.smi.v1_2.ObjectFactory.class, com.dolby.dcinema.ws.smi.v1_1.ObjectFactory.class, com.dolby.dcinema.ws.smi.v1_0.ObjectFactory.class, com.dolby.dcinema.ws.smi.v1.schemas.fault.ObjectFactory.class, com.dolby.dcinema.ws.smi.v1.schemas.playbackcontrol.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface PlaybackControlServiceV13 {

    /**
     * @see portType PlaybackControlService_v1_1
     *       
     */
    @WebResult(name = "setAutoPlaybackModeResponse", targetNamespace = "http://www.dolby.com/dcinema/ws/smi/v1_1", partName = "result")
    @WebMethod(action = "http://www.dolby.com/dcinema/ws/smi/v1/setAutoPlaybackMode")
    public com.dolby.dcinema.ws.smi.v1_1.SetAutoPlaybackModeResponse setAutoPlaybackMode(
        @WebParam(partName = "parameters", name = "setAutoPlaybackModeRequest", targetNamespace = "http://www.dolby.com/dcinema/ws/smi/v1_1")
        com.dolby.dcinema.ws.smi.v1_1.SetAutoPlaybackModeRequest parameters
    ) throws Fault;

    /**
     * @see portType PlaybackControlService_v1_0
     *       
     */
    @WebResult(name = "playResponse", targetNamespace = "http://www.dolby.com/dcinema/ws/smi/v1_0", partName = "result")
    @WebMethod(action = "http://www.dolby.com/dcinema/ws/smi/v1/play")
    public com.dolby.dcinema.ws.smi.v1_0.PlayResponse play(
        @WebParam(partName = "parameters", name = "playRequest", targetNamespace = "http://www.dolby.com/dcinema/ws/smi/v1_0")
        com.dolby.dcinema.ws.smi.v1_0.PlayRequest parameters
    ) throws Fault;

    /**
     * getPlaybackState2 Operation
     *     Gets the current playback state; allowing for the return of PlaybackMode2
     * 
     * 		  Parameters:
     * 		      None
     * 
     * 		  Response:
     * 		      transportState - Indicates the current state of the transport.
     * 		      contentPlaybackState (optional) - Indicates the state of the currently selected
     * 		          content.  Will only be present if content is selected.
     * 			  scheduleMode - Indicates whether content will automatically play off of the schedule.
     * 			  playbackMode - Indicates what mode the player will play in (2D, 3D, Dolby 3D, Real D).
     * 
     * 		  Exceptions:
     * 		      NotConnected - If the ContentPlayer component is not connected.
     * 
     * 		  Related Services:
     * 		      None
     *       
     */
    @WebResult(name = "getPlaybackState2Response", targetNamespace = "http://www.dolby.com/dcinema/ws/smi/v1_3", partName = "result")
    @WebMethod(action = "http://www.dolby.com/dcinema/ws/smi/v1/getPlaybackState2")
    public com.dolby.dcinema.ws.smi.v1_3.GetPlaybackState2Response getPlaybackState2(
        @WebParam(partName = "parameters", name = "getPlaybackState2Request", targetNamespace = "http://www.dolby.com/dcinema/ws/smi/v1_3")
        com.dolby.dcinema.ws.smi.v1_3.GetPlaybackState2Request parameters
    ) throws Fault;

    /**
     * @see portType PlaybackControlService_v1_0
     *       
     */
    @WebResult(name = "goToPositionResponse", targetNamespace = "http://www.dolby.com/dcinema/ws/smi/v1_0", partName = "result")
    @WebMethod(action = "http://www.dolby.com/dcinema/ws/smi/v1/goToPosition")
    public com.dolby.dcinema.ws.smi.v1_0.GoToPositionResponse goToPosition(
        @WebParam(partName = "parameters", name = "goToPositionRequest", targetNamespace = "http://www.dolby.com/dcinema/ws/smi/v1_0")
        com.dolby.dcinema.ws.smi.v1_0.GoToPositionRequest parameters
    ) throws Fault;

    /**
     * @see portType PlaybackControlService_v1_2
     *       
     */
    @WebResult(name = "getPrepSuiteStateResponse", targetNamespace = "http://www.dolby.com/dcinema/ws/smi/v1_2", partName = "result")
    @WebMethod(action = "http://www.dolby.com/dcinema/ws/smi/v1/getPrepSuiteState")
    public com.dolby.dcinema.ws.smi.v1_2.GetPrepSuiteStateResponse getPrepSuiteState(
        @WebParam(partName = "parameters", name = "getPrepSuiteStateRequest", targetNamespace = "http://www.dolby.com/dcinema/ws/smi/v1_2")
        com.dolby.dcinema.ws.smi.v1_2.GetPrepSuiteStateRequest parameters
    ) throws Fault;

    /**
     * @see portType PlaybackControlService_v1_0
     *       
     */
    @WebResult(name = "getScheduleModeResponse", targetNamespace = "http://www.dolby.com/dcinema/ws/smi/v1_0", partName = "result")
    @WebMethod(action = "http://www.dolby.com/dcinema/ws/smi/v1/getScheduleMode")
    public com.dolby.dcinema.ws.smi.v1_0.GetScheduleModeResponse getScheduleMode(
        @WebParam(partName = "parameters", name = "getScheduleModeRequest", targetNamespace = "http://www.dolby.com/dcinema/ws/smi/v1_0")
        com.dolby.dcinema.ws.smi.v1_0.GetScheduleModeRequest parameters
    ) throws Fault;

    /**
     * @see portType PlaybackControlService_v1_1
     *       
     */
    @WebResult(name = "fireCueResponse", targetNamespace = "http://www.dolby.com/dcinema/ws/smi/v1_1", partName = "result")
    @WebMethod(action = "http://www.dolby.com/dcinema/ws/smi/v1/fireCue")
    public com.dolby.dcinema.ws.smi.v1_1.FireCueResponse fireCue(
        @WebParam(partName = "parameters", name = "fireCueRequest", targetNamespace = "http://www.dolby.com/dcinema/ws/smi/v1_1")
        com.dolby.dcinema.ws.smi.v1_1.FireCueRequest parameters
    ) throws Fault;

    /**
     * setAutoPlaybackMode2 Operation
     *     Sets the auto playback mode (Manual, 3D, Dolby 3D, RealD) of the player.
     *     
     * 		  Parameters:
     * 		      autoPlaybackMode - The new auto playback mode of the player.
     * 
     * 		  Response:
     *     None
     * 
     * 		  Related Services:
     * 		      getAutoPlaybackMode2 - Used to obtain the current auto playback mode. 
     *       
     */
    @WebResult(name = "setAutoPlaybackMode2Response", targetNamespace = "http://www.dolby.com/dcinema/ws/smi/v1_3", partName = "result")
    @WebMethod(action = "http://www.dolby.com/dcinema/ws/smi/v1/setAutoPlaybackMode2")
    public com.dolby.dcinema.ws.smi.v1_3.SetAutoPlaybackMode2Response setAutoPlaybackMode2(
        @WebParam(partName = "parameters", name = "setAutoPlaybackMode2Request", targetNamespace = "http://www.dolby.com/dcinema/ws/smi/v1_3")
        com.dolby.dcinema.ws.smi.v1_3.SetAutoPlaybackMode2Request parameters
    ) throws Fault;

    /**
     * @see portType PlaybackControlService_v1_1
     *       
     */
    @WebResult(name = "getAutoPlaybackModeResponse", targetNamespace = "http://www.dolby.com/dcinema/ws/smi/v1_1", partName = "result")
    @WebMethod(action = "http://www.dolby.com/dcinema/ws/smi/v1/getAutoPlaybackMode")
    public com.dolby.dcinema.ws.smi.v1_1.GetAutoPlaybackModeResponse getAutoPlaybackMode(
        @WebParam(partName = "parameters", name = "getAutoPlaybackModeRequest", targetNamespace = "http://www.dolby.com/dcinema/ws/smi/v1_1")
        com.dolby.dcinema.ws.smi.v1_1.GetAutoPlaybackModeRequest parameters
    ) throws Fault;

    /**
     * @see portType PlaybackControlService_v1_1
     *       
     */
    @WebResult(name = "getPurgeSuiteStateResponse", targetNamespace = "http://www.dolby.com/dcinema/ws/smi/v1_1", partName = "result")
    @WebMethod(action = "http://www.dolby.com/dcinema/ws/smi/v1/getPurgeSuiteState")
    public com.dolby.dcinema.ws.smi.v1_1.GetPurgeSuiteStateResponse getPurgeSuiteState(
        @WebParam(partName = "parameters", name = "getPurgeSuiteStateRequest", targetNamespace = "http://www.dolby.com/dcinema/ws/smi/v1_1")
        com.dolby.dcinema.ws.smi.v1_1.GetPurgeSuiteStateRequest parameters
    ) throws Fault;

    /**
     * @see portType PlaybackControlService_v1_0
     *       
     */
    @WebResult(name = "getPlaybackStateResponse", targetNamespace = "http://www.dolby.com/dcinema/ws/smi/v1_0", partName = "result")
    @WebMethod(action = "http://www.dolby.com/dcinema/ws/smi/v1/getPlaybackState")
    public com.dolby.dcinema.ws.smi.v1_0.GetPlaybackStateResponse getPlaybackState(
        @WebParam(partName = "parameters", name = "getPlaybackStateRequest", targetNamespace = "http://www.dolby.com/dcinema/ws/smi/v1_0")
        com.dolby.dcinema.ws.smi.v1_0.GetPlaybackStateRequest parameters
    ) throws Fault;

    /**
     * @see portType PlaybackControlService_v1_0
     *       
     */
    @WebResult(name = "setScheduleModeResponse", targetNamespace = "http://www.dolby.com/dcinema/ws/smi/v1_0", partName = "result")
    @WebMethod(action = "http://www.dolby.com/dcinema/ws/smi/v1/setScheduleMode")
    public com.dolby.dcinema.ws.smi.v1_0.SetScheduleModeResponse setScheduleMode(
        @WebParam(partName = "parameters", name = "setScheduleModeRequest", targetNamespace = "http://www.dolby.com/dcinema/ws/smi/v1_0")
        com.dolby.dcinema.ws.smi.v1_0.SetScheduleModeRequest parameters
    ) throws Fault;

    /**
     * @see portType PlaybackControlService_v1_0
     *       
     */
    @WebResult(name = "nextResponse", targetNamespace = "http://www.dolby.com/dcinema/ws/smi/v1_0", partName = "result")
    @WebMethod(action = "http://www.dolby.com/dcinema/ws/smi/v1/next")
    public com.dolby.dcinema.ws.smi.v1_0.NextResponse next(
        @WebParam(partName = "parameters", name = "nextRequest", targetNamespace = "http://www.dolby.com/dcinema/ws/smi/v1_0")
        com.dolby.dcinema.ws.smi.v1_0.NextRequest parameters
    ) throws Fault;

    /**
     * getAutoPlaybackMode2 Operation
     *    Gets the current auto playback mode; allowing for RealD 3D mode and other extension values.
     * 
     * 		  Parameters:
     * 		      None
     * 
     * 		  Response:
     * 			  autoPlaybackMode - Indicates what playback mode the player will use for playing 3D content.
     * 			                     3D content may be played back in 2D mode if MANUAL is selected.
     * 
     * 		  Related Services:
     * 		      setAutoPlaybackMode2 - Used to set the current auto playback mode.
     *       
     */
    @WebResult(name = "getAutoPlaybackMode2Response", targetNamespace = "http://www.dolby.com/dcinema/ws/smi/v1_3", partName = "result")
    @WebMethod(action = "http://www.dolby.com/dcinema/ws/smi/v1/getAutoPlaybackMode2")
    public com.dolby.dcinema.ws.smi.v1_3.GetAutoPlaybackMode2Response getAutoPlaybackMode2(
        @WebParam(partName = "parameters", name = "getAutoPlaybackMode2Request", targetNamespace = "http://www.dolby.com/dcinema/ws/smi/v1_3")
        com.dolby.dcinema.ws.smi.v1_3.GetAutoPlaybackMode2Request parameters
    ) throws Fault;

    /**
     * @see portType PlaybackControlService_v1_0
     *       
     */
    @WebResult(name = "pauseResponse", targetNamespace = "http://www.dolby.com/dcinema/ws/smi/v1_0", partName = "result")
    @WebMethod(action = "http://www.dolby.com/dcinema/ws/smi/v1/pause")
    public com.dolby.dcinema.ws.smi.v1_0.PauseResponse pause(
        @WebParam(partName = "parameters", name = "pauseRequest", targetNamespace = "http://www.dolby.com/dcinema/ws/smi/v1_0")
        com.dolby.dcinema.ws.smi.v1_0.PauseRequest parameters
    ) throws Fault;

    /**
     * @see portType PlaybackControlService_v1_0
     *       
     */
    @WebResult(name = "stopResponse", targetNamespace = "http://www.dolby.com/dcinema/ws/smi/v1_0", partName = "result")
    @WebMethod(action = "http://www.dolby.com/dcinema/ws/smi/v1/stop")
    public com.dolby.dcinema.ws.smi.v1_0.StopResponse stop(
        @WebParam(partName = "parameters", name = "stopRequest", targetNamespace = "http://www.dolby.com/dcinema/ws/smi/v1_0")
        com.dolby.dcinema.ws.smi.v1_0.StopRequest parameters
    ) throws Fault;

    /**
     * setPlaybackMode2 Operation
     *     Sets the playback mode (2D, 3D, Dolby 3D, RealD) of the player.
     * 
     * 		  Parameters:
     * 		      playbackMode - The new playback mode of the player.
     * 
     * 		  Response:
     *     None
     * 
     * 		  Exceptions:
     * 		      NotConnected - If the Decoder component is not connected.
     * 		      OperationFailed - if the playback mode cannot be changed because autoPlaybackMode is not set to MANUAL.
     * 
     * 		  Related Services:
     * 		      getPlaybackState2 - Successfully initiating setPlaybackMode2 indicates that the request succeeded.
     * 		         The service getPlaybackState2 should be used to ensure the desired playback mode.
     *       
     */
    @WebResult(name = "setPlaybackMode2Response", targetNamespace = "http://www.dolby.com/dcinema/ws/smi/v1_3", partName = "result")
    @WebMethod(action = "http://www.dolby.com/dcinema/ws/smi/v1/setPlaybackMode2")
    public com.dolby.dcinema.ws.smi.v1_3.SetPlaybackMode2Response setPlaybackMode2(
        @WebParam(partName = "parameters", name = "setPlaybackMode2Request", targetNamespace = "http://www.dolby.com/dcinema/ws/smi/v1_3")
        com.dolby.dcinema.ws.smi.v1_3.SetPlaybackMode2Request parameters
    ) throws Fault;

    /**
     * @see portType PlaybackControlService_v1_0
     *       
     */
    @WebResult(name = "setPlaybackModeResponse", targetNamespace = "http://www.dolby.com/dcinema/ws/smi/v1_0", partName = "result")
    @WebMethod(action = "http://www.dolby.com/dcinema/ws/smi/v1/setPlaybackMode")
    public com.dolby.dcinema.ws.smi.v1_0.SetPlaybackModeResponse setPlaybackMode(
        @WebParam(partName = "parameters", name = "setPlaybackModeRequest", targetNamespace = "http://www.dolby.com/dcinema/ws/smi/v1_0")
        com.dolby.dcinema.ws.smi.v1_0.SetPlaybackModeRequest parameters
    ) throws Fault;

    /**
     * @see portType PlaybackControlService_v1_0
     *       
     */
    @WebResult(name = "previousResponse", targetNamespace = "http://www.dolby.com/dcinema/ws/smi/v1_0", partName = "result")
    @WebMethod(action = "http://www.dolby.com/dcinema/ws/smi/v1/previous")
    public com.dolby.dcinema.ws.smi.v1_0.PreviousResponse previous(
        @WebParam(partName = "parameters", name = "previousRequest", targetNamespace = "http://www.dolby.com/dcinema/ws/smi/v1_0")
        com.dolby.dcinema.ws.smi.v1_0.PreviousRequest parameters
    ) throws Fault;

    /**
     * @see portType PlaybackControlService_v1_0
     *       
     */
    @WebResult(name = "selectContentResponse", targetNamespace = "http://www.dolby.com/dcinema/ws/smi/v1_0", partName = "result")
    @WebMethod(action = "http://www.dolby.com/dcinema/ws/smi/v1/selectContent")
    public com.dolby.dcinema.ws.smi.v1_0.SelectContentResponse selectContent(
        @WebParam(partName = "parameters", name = "selectContentRequest", targetNamespace = "http://www.dolby.com/dcinema/ws/smi/v1_0")
        com.dolby.dcinema.ws.smi.v1_0.SelectContentRequest parameters
    ) throws Fault;
}
