/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.dolby.dcinema.ws.smi.v1;

import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 3.1.1 2015-07-09T17:38:11.428+02:00
 * Generated source version: 3.1.1
 * 
 */

@javax.jws.WebService(serviceName = "PlaybackControl_v1_0", portName = "PlaybackControlService_v1_0", targetNamespace = "http://www.dolby.com/dcinema/ws/smi/v1", wsdlLocation = "dolby-smi/PlaybackControl.wsdl", endpointInterface = "com.dolby.dcinema.ws.smi.v1.PlaybackControlServiceV10")
public class PlaybackControlService_V1_0Impl2 implements PlaybackControlServiceV10 {

	private static final Logger LOG = Logger.getLogger(PlaybackControlService_V1_0Impl2.class
	        .getName());

	/* (non-Javadoc)
	 * 
	 * @see
	 * com.dolby.dcinema.ws.smi.v1.PlaybackControlServiceV10#play(com.dolby
	 * .dcinema.ws.smi.v1_0.PlayRequest parameters )* */
	public com.dolby.dcinema.ws.smi.v1_0.PlayResponse play(
	        com.dolby.dcinema.ws.smi.v1_0.PlayRequest parameters) throws Fault {
		LOG.info("Executing operation play");
		System.out.println(parameters);
		try {
			com.dolby.dcinema.ws.smi.v1_0.PlayResponse _return = null;
			return _return;
		} catch (java.lang.Exception ex) {
			ex.printStackTrace();
			throw new RuntimeException(ex);
		}
		// throw new Fault("fault...");
	}

	/* (non-Javadoc)
	 * 
	 * @see
	 * com.dolby.dcinema.ws.smi.v1.PlaybackControlServiceV10#goToPosition(com
	 * .dolby.dcinema.ws.smi.v1_0.GoToPositionRequest parameters )* */
	public com.dolby.dcinema.ws.smi.v1_0.GoToPositionResponse goToPosition(
	        com.dolby.dcinema.ws.smi.v1_0.GoToPositionRequest parameters) throws Fault {
		LOG.info("Executing operation goToPosition");
		System.out.println(parameters);
		try {
			com.dolby.dcinema.ws.smi.v1_0.GoToPositionResponse _return = null;
			return _return;
		} catch (java.lang.Exception ex) {
			ex.printStackTrace();
			throw new RuntimeException(ex);
		}
		// throw new Fault("fault...");
	}

	/* (non-Javadoc)
	 * 
	 * @see
	 * com.dolby.dcinema.ws.smi.v1.PlaybackControlServiceV10#getScheduleMode
	 * (com.dolby.dcinema.ws.smi.v1_0.GetScheduleModeRequest parameters )* */
	public com.dolby.dcinema.ws.smi.v1_0.GetScheduleModeResponse getScheduleMode(
	        com.dolby.dcinema.ws.smi.v1_0.GetScheduleModeRequest parameters) throws Fault {
		LOG.info("Executing operation getScheduleMode");
		System.out.println(parameters);
		try {
			com.dolby.dcinema.ws.smi.v1_0.GetScheduleModeResponse _return = null;
			return _return;
		} catch (java.lang.Exception ex) {
			ex.printStackTrace();
			throw new RuntimeException(ex);
		}
		// throw new Fault("fault...");
	}

	/* (non-Javadoc)
	 * 
	 * @see
	 * com.dolby.dcinema.ws.smi.v1.PlaybackControlServiceV10#stop(com.dolby
	 * .dcinema.ws.smi.v1_0.StopRequest parameters )* */
	public com.dolby.dcinema.ws.smi.v1_0.StopResponse stop(
	        com.dolby.dcinema.ws.smi.v1_0.StopRequest parameters) throws Fault {
		LOG.info("Executing operation stop");
		System.out.println(parameters);
		try {
			com.dolby.dcinema.ws.smi.v1_0.StopResponse _return = null;
			return _return;
		} catch (java.lang.Exception ex) {
			ex.printStackTrace();
			throw new RuntimeException(ex);
		}
		// throw new Fault("fault...");
	}

	/* (non-Javadoc)
	 * 
	 * @see
	 * com.dolby.dcinema.ws.smi.v1.PlaybackControlServiceV10#getPlaybackState
	 * (com.dolby.dcinema.ws.smi.v1_0.GetPlaybackStateRequest parameters )* */
	public com.dolby.dcinema.ws.smi.v1_0.GetPlaybackStateResponse getPlaybackState(
	        com.dolby.dcinema.ws.smi.v1_0.GetPlaybackStateRequest parameters) throws Fault {
		LOG.info("Executing operation getPlaybackState");
		System.out.println(parameters);
		try {
			com.dolby.dcinema.ws.smi.v1_0.GetPlaybackStateResponse _return = null;
			return _return;
		} catch (java.lang.Exception ex) {
			ex.printStackTrace();
			throw new RuntimeException(ex);
		}
		// throw new Fault("fault...");
	}

	/* (non-Javadoc)
	 * 
	 * @see
	 * com.dolby.dcinema.ws.smi.v1.PlaybackControlServiceV10#setScheduleMode
	 * (com.dolby.dcinema.ws.smi.v1_0.SetScheduleModeRequest parameters )* */
	public com.dolby.dcinema.ws.smi.v1_0.SetScheduleModeResponse setScheduleMode(
	        com.dolby.dcinema.ws.smi.v1_0.SetScheduleModeRequest parameters) throws Fault {
		LOG.info("Executing operation setScheduleMode");
		System.out.println(parameters);
		try {
			com.dolby.dcinema.ws.smi.v1_0.SetScheduleModeResponse _return = null;
			return _return;
		} catch (java.lang.Exception ex) {
			ex.printStackTrace();
			throw new RuntimeException(ex);
		}
		// throw new Fault("fault...");
	}

	/* (non-Javadoc)
	 * 
	 * @see
	 * com.dolby.dcinema.ws.smi.v1.PlaybackControlServiceV10#next(com.dolby
	 * .dcinema.ws.smi.v1_0.NextRequest parameters )* */
	public com.dolby.dcinema.ws.smi.v1_0.NextResponse next(
	        com.dolby.dcinema.ws.smi.v1_0.NextRequest parameters) throws Fault {
		LOG.info("Executing operation next");
		System.out.println(parameters);
		try {
			com.dolby.dcinema.ws.smi.v1_0.NextResponse _return = null;
			return _return;
		} catch (java.lang.Exception ex) {
			ex.printStackTrace();
			throw new RuntimeException(ex);
		}
		// throw new Fault("fault...");
	}

	/* (non-Javadoc)
	 * 
	 * @see
	 * com.dolby.dcinema.ws.smi.v1.PlaybackControlServiceV10#setPlaybackMode
	 * (com.dolby.dcinema.ws.smi.v1_0.SetPlaybackModeRequest parameters )* */
	public com.dolby.dcinema.ws.smi.v1_0.SetPlaybackModeResponse setPlaybackMode(
	        com.dolby.dcinema.ws.smi.v1_0.SetPlaybackModeRequest parameters) throws Fault {
		LOG.info("Executing operation setPlaybackMode");
		System.out.println(parameters);
		try {
			com.dolby.dcinema.ws.smi.v1_0.SetPlaybackModeResponse _return = null;
			return _return;
		} catch (java.lang.Exception ex) {
			ex.printStackTrace();
			throw new RuntimeException(ex);
		}
		// throw new Fault("fault...");
	}

	/* (non-Javadoc)
	 * 
	 * @see
	 * com.dolby.dcinema.ws.smi.v1.PlaybackControlServiceV10#previous(com.dolby
	 * .dcinema.ws.smi.v1_0.PreviousRequest parameters )* */
	public com.dolby.dcinema.ws.smi.v1_0.PreviousResponse previous(
	        com.dolby.dcinema.ws.smi.v1_0.PreviousRequest parameters) throws Fault {
		LOG.info("Executing operation previous");
		System.out.println(parameters);
		try {
			com.dolby.dcinema.ws.smi.v1_0.PreviousResponse _return = null;
			return _return;
		} catch (java.lang.Exception ex) {
			ex.printStackTrace();
			throw new RuntimeException(ex);
		}
		// throw new Fault("fault...");
	}

	/* (non-Javadoc)
	 * 
	 * @see
	 * com.dolby.dcinema.ws.smi.v1.PlaybackControlServiceV10#selectContent(
	 * com.dolby.dcinema.ws.smi.v1_0.SelectContentRequest parameters )* */
	public com.dolby.dcinema.ws.smi.v1_0.SelectContentResponse selectContent(
	        com.dolby.dcinema.ws.smi.v1_0.SelectContentRequest parameters) throws Fault {
		LOG.info("Executing operation selectContent");
		System.out.println(parameters);
		try {
			com.dolby.dcinema.ws.smi.v1_0.SelectContentResponse _return = null;
			return _return;
		} catch (java.lang.Exception ex) {
			ex.printStackTrace();
			throw new RuntimeException(ex);
		}
		// throw new Fault("fault...");
	}

	/* (non-Javadoc)
	 * 
	 * @see
	 * com.dolby.dcinema.ws.smi.v1.PlaybackControlServiceV10#pause(com.dolby
	 * .dcinema.ws.smi.v1_0.PauseRequest parameters )* */
	public com.dolby.dcinema.ws.smi.v1_0.PauseResponse pause(
	        com.dolby.dcinema.ws.smi.v1_0.PauseRequest parameters) throws Fault {
		LOG.info("Executing operation pause");
		System.out.println(parameters);
		try {
			com.dolby.dcinema.ws.smi.v1_0.PauseResponse _return = null;
			return _return;
		} catch (java.lang.Exception ex) {
			ex.printStackTrace();
			throw new RuntimeException(ex);
		}
		// throw new Fault("fault...");
	}

}
