//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.29 at 10:25:38 AM CEST 
//


package com.cineapps.dolby.show;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.cineapps.show package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ShowPlaylistShowCompositionPlaylistIdAnnotationText_QNAME = new QName("http://www.dolby.com/dcinema/ws/smi/v11/SPL", "AnnotationText");
    private final static QName _ShowPlaylistShowCompositionPlaylistIdLabel_QNAME = new QName("http://www.dolby.com/dcinema/ws/smi/v11/SPL", "Label");
    private final static QName _ShowPlaylistShowCompositionPlaylistIdId_QNAME = new QName("http://www.dolby.com/dcinema/ws/smi/v11/SPL", "Id");
    private final static QName _ShowPlaylistShowCompositionPlaylistIdOffset_QNAME = new QName("http://www.dolby.com/dcinema/ws/smi/v11/SPL", "Offset");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.cineapps.show
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ShowPlaylist }
     * 
     */
    public ShowPlaylist createShowPlaylist() {
        return new ShowPlaylist();
    }

    /**
     * Create an instance of {@link ShowPlaylist.Show }
     * 
     */
    public ShowPlaylist.Show createShowPlaylistShow() {
        return new ShowPlaylist.Show();
    }

    /**
     * Create an instance of {@link ShowPlaylist.Show.CompositionPlaylistId }
     * 
     */
    public ShowPlaylist.Show.CompositionPlaylistId createShowPlaylistShowCompositionPlaylistId() {
        return new ShowPlaylist.Show.CompositionPlaylistId();
    }

    /**
     * Create an instance of {@link ShowPlaylist.Show.Marker }
     * 
     */
    public ShowPlaylist.Show.Marker createShowPlaylistShowMarker() {
        return new ShowPlaylist.Show.Marker();
    }

    /**
     * Create an instance of {@link ShowPlaylist.ArrangementId }
     * 
     */
    public ShowPlaylist.ArrangementId createShowPlaylistArrangementId() {
        return new ShowPlaylist.ArrangementId();
    }

    /**
     * Create an instance of {@link ShowPlaylist.AnnotationText }
     * 
     */
    public ShowPlaylist.AnnotationText createShowPlaylistAnnotationText() {
        return new ShowPlaylist.AnnotationText();
    }

    /**
     * Create an instance of {@link ShowPlaylist.Creator }
     * 
     */
    public ShowPlaylist.Creator createShowPlaylistCreator() {
        return new ShowPlaylist.Creator();
    }

    /**
     * Create an instance of {@link ShowPlaylist.Issuer }
     * 
     */
    public ShowPlaylist.Issuer createShowPlaylistIssuer() {
        return new ShowPlaylist.Issuer();
    }

    /**
     * Create an instance of {@link ShowPlaylist.ShowTitleText }
     * 
     */
    public ShowPlaylist.ShowTitleText createShowPlaylistShowTitleText() {
        return new ShowPlaylist.ShowTitleText();
    }

    /**
     * Create an instance of {@link ShowPlaylist.Show.CompositionPlaylistId.AnnotationText }
     * 
     */
    public ShowPlaylist.Show.CompositionPlaylistId.AnnotationText createShowPlaylistShowCompositionPlaylistIdAnnotationText() {
        return new ShowPlaylist.Show.CompositionPlaylistId.AnnotationText();
    }

    /**
     * Create an instance of {@link ShowPlaylist.Show.CompositionPlaylistId.Label }
     * 
     */
    public ShowPlaylist.Show.CompositionPlaylistId.Label createShowPlaylistShowCompositionPlaylistIdLabel() {
        return new ShowPlaylist.Show.CompositionPlaylistId.Label();
    }

    /**
     * Create an instance of {@link ShowPlaylist.Show.CompositionPlaylistId.Offset }
     * 
     */
    public ShowPlaylist.Show.CompositionPlaylistId.Offset createShowPlaylistShowCompositionPlaylistIdOffset() {
        return new ShowPlaylist.Show.CompositionPlaylistId.Offset();
    }

    /**
     * Create an instance of {@link ShowPlaylist.Show.Marker.AnnotationText }
     * 
     */
    public ShowPlaylist.Show.Marker.AnnotationText createShowPlaylistShowMarkerAnnotationText() {
        return new ShowPlaylist.Show.Marker.AnnotationText();
    }

    /**
     * Create an instance of {@link ShowPlaylist.Show.Marker.Label }
     * 
     */
    public ShowPlaylist.Show.Marker.Label createShowPlaylistShowMarkerLabel() {
        return new ShowPlaylist.Show.Marker.Label();
    }

    /**
     * Create an instance of {@link ShowPlaylist.Show.Marker.Offset }
     * 
     */
    public ShowPlaylist.Show.Marker.Offset createShowPlaylistShowMarkerOffset() {
        return new ShowPlaylist.Show.Marker.Offset();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ShowPlaylist.Show.CompositionPlaylistId.AnnotationText }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.dolby.com/dcinema/ws/smi/v11/SPL", name = "AnnotationText", scope = ShowPlaylist.Show.CompositionPlaylistId.class)
    public JAXBElement<ShowPlaylist.Show.CompositionPlaylistId.AnnotationText> createShowPlaylistShowCompositionPlaylistIdAnnotationText(ShowPlaylist.Show.CompositionPlaylistId.AnnotationText value) {
        return new JAXBElement<ShowPlaylist.Show.CompositionPlaylistId.AnnotationText>(_ShowPlaylistShowCompositionPlaylistIdAnnotationText_QNAME, ShowPlaylist.Show.CompositionPlaylistId.AnnotationText.class, ShowPlaylist.Show.CompositionPlaylistId.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ShowPlaylist.Show.CompositionPlaylistId.Label }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.dolby.com/dcinema/ws/smi/v11/SPL", name = "Label", scope = ShowPlaylist.Show.CompositionPlaylistId.class)
    public JAXBElement<ShowPlaylist.Show.CompositionPlaylistId.Label> createShowPlaylistShowCompositionPlaylistIdLabel(ShowPlaylist.Show.CompositionPlaylistId.Label value) {
        return new JAXBElement<ShowPlaylist.Show.CompositionPlaylistId.Label>(_ShowPlaylistShowCompositionPlaylistIdLabel_QNAME, ShowPlaylist.Show.CompositionPlaylistId.Label.class, ShowPlaylist.Show.CompositionPlaylistId.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.dolby.com/dcinema/ws/smi/v11/SPL", name = "Id", scope = ShowPlaylist.Show.CompositionPlaylistId.class)
    public JAXBElement<String> createShowPlaylistShowCompositionPlaylistIdId(String value) {
        return new JAXBElement<String>(_ShowPlaylistShowCompositionPlaylistIdId_QNAME, String.class, ShowPlaylist.Show.CompositionPlaylistId.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ShowPlaylist.Show.CompositionPlaylistId.Offset }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.dolby.com/dcinema/ws/smi/v11/SPL", name = "Offset", scope = ShowPlaylist.Show.CompositionPlaylistId.class)
    public JAXBElement<ShowPlaylist.Show.CompositionPlaylistId.Offset> createShowPlaylistShowCompositionPlaylistIdOffset(ShowPlaylist.Show.CompositionPlaylistId.Offset value) {
        return new JAXBElement<ShowPlaylist.Show.CompositionPlaylistId.Offset>(_ShowPlaylistShowCompositionPlaylistIdOffset_QNAME, ShowPlaylist.Show.CompositionPlaylistId.Offset.class, ShowPlaylist.Show.CompositionPlaylistId.class, value);
    }

}
