//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.29 at 10:25:38 AM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.dolby.com/dcinema/ws/smi/v11/SPL", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.cineapps.dolby.show;
