//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.03 at 05:38:02 PM CEST 
//

package com.cineapps.acs_ftp.model;

import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.JAXBContext;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.stream.XMLInputFactory;
import javax.xml.stream.XMLStreamReader;

import org.apache.log4j.Logger;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AnnotationText" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="IssueDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="Issuer" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Creator" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ContentTitleText" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ContentKind" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="RatingList" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ReelList">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Reel" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="AssetList">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="MainPicture">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="EditRate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="IntrinsicDuration" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                                                 &lt;element name="EntryPoint" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                                                 &lt;element name="Duration" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                                                 &lt;element name="KeyId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="Hash" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="FrameRate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="ScreenAspectRatio" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                       &lt;element name="MainSound">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="EditRate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="IntrinsicDuration" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                                                 &lt;element name="EntryPoint" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                                                 &lt;element name="Duration" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                                                 &lt;element name="KeyId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="Hash" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                       &lt;element name="MainSubtitle" minOccurs="0">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="EditRate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="IntrinsicDuration" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                                                 &lt;element name="EntryPoint" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                                                 &lt;element name="Duration" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                                                 &lt;element name="Hash" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "id", "annotationText", "issueDate", "issuer", "creator",
        "contentTitleText", "contentKind", "ratingList", "reelList" })
@XmlRootElement(name = "CompositionPlaylist")
public class CompositionPlaylist {

	@XmlElement(name = "Id", required = true)
	protected String id;
	@XmlElement(name = "AnnotationText", required = true)
	protected String annotationText;
	@XmlElement(name = "IssueDate", required = true)
	@XmlSchemaType(name = "dateTime")
	protected XMLGregorianCalendar issueDate;
	@XmlElement(name = "Issuer", required = true)
	protected String issuer;
	@XmlElement(name = "Creator", required = true)
	protected String creator;
	@XmlElement(name = "ContentTitleText", required = true)
	protected String contentTitleText;
	@XmlElement(name = "ContentKind", required = true)
	protected String contentKind;
	@XmlElement(name = "RatingList", required = true)
	protected String ratingList;
	@XmlElement(name = "ReelList", required = true)
	protected CompositionPlaylist.ReelList reelList;

	/**
	 * Gets the value of the id property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getId() {
		return id;
	}

	/**
	 * Sets the value of the id property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setId(String value) {
		this.id = value;
	}

	/**
	 * Gets the value of the annotationText property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getAnnotationText() {
		return annotationText;
	}

	/**
	 * Sets the value of the annotationText property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setAnnotationText(String value) {
		this.annotationText = value;
	}

	/**
	 * Gets the value of the issueDate property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 * 
	 */
	public XMLGregorianCalendar getIssueDate() {
		return issueDate;
	}

	/**
	 * Sets the value of the issueDate property.
	 * 
	 * @param value
	 *            allowed object is {@link XMLGregorianCalendar }
	 * 
	 */
	public void setIssueDate(XMLGregorianCalendar value) {
		this.issueDate = value;
	}

	/**
	 * Gets the value of the issuer property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getIssuer() {
		return issuer;
	}

	/**
	 * Sets the value of the issuer property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setIssuer(String value) {
		this.issuer = value;
	}

	/**
	 * Gets the value of the creator property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCreator() {
		return creator;
	}

	/**
	 * Sets the value of the creator property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCreator(String value) {
		this.creator = value;
	}

	/**
	 * Gets the value of the contentTitleText property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getContentTitleText() {
		return contentTitleText;
	}

	/**
	 * Sets the value of the contentTitleText property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setContentTitleText(String value) {
		this.contentTitleText = value;
	}

	/**
	 * Gets the value of the contentKind property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getContentKind() {
		return contentKind;
	}

	/**
	 * Sets the value of the contentKind property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setContentKind(String value) {
		this.contentKind = value;
	}

	/**
	 * Gets the value of the ratingList property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getRatingList() {
		return ratingList;
	}

	/**
	 * Sets the value of the ratingList property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setRatingList(String value) {
		this.ratingList = value;
	}

	/**
	 * Gets the value of the reelList property.
	 * 
	 * @return possible object is {@link CompositionPlaylist.ReelList }
	 * 
	 */
	public CompositionPlaylist.ReelList getReelList() {
		return reelList;
	}

	/**
	 * Sets the value of the reelList property.
	 * 
	 * @param value
	 *            allowed object is {@link CompositionPlaylist.ReelList }
	 * 
	 */
	public void setReelList(CompositionPlaylist.ReelList value) {
		this.reelList = value;
	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="Reel" maxOccurs="unbounded" minOccurs="0">
	 *           &lt;complexType>
	 *             &lt;complexContent>
	 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                 &lt;sequence>
	 *                   &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *                   &lt;element name="AssetList">
	 *                     &lt;complexType>
	 *                       &lt;complexContent>
	 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                           &lt;sequence>
	 *                             &lt;element name="MainPicture">
	 *                               &lt;complexType>
	 *                                 &lt;complexContent>
	 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                                     &lt;sequence>
	 *                                       &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *                                       &lt;element name="EditRate" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *                                       &lt;element name="IntrinsicDuration" type="{http://www.w3.org/2001/XMLSchema}short"/>
	 *                                       &lt;element name="EntryPoint" type="{http://www.w3.org/2001/XMLSchema}short"/>
	 *                                       &lt;element name="Duration" type="{http://www.w3.org/2001/XMLSchema}short"/>
	 *                                       &lt;element name="KeyId" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *                                       &lt;element name="Hash" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *                                       &lt;element name="FrameRate" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *                                       &lt;element name="ScreenAspectRatio" type="{http://www.w3.org/2001/XMLSchema}float"/>
	 *                                     &lt;/sequence>
	 *                                   &lt;/restriction>
	 *                                 &lt;/complexContent>
	 *                               &lt;/complexType>
	 *                             &lt;/element>
	 *                             &lt;element name="MainSound">
	 *                               &lt;complexType>
	 *                                 &lt;complexContent>
	 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                                     &lt;sequence>
	 *                                       &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *                                       &lt;element name="EditRate" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *                                       &lt;element name="IntrinsicDuration" type="{http://www.w3.org/2001/XMLSchema}short"/>
	 *                                       &lt;element name="EntryPoint" type="{http://www.w3.org/2001/XMLSchema}short"/>
	 *                                       &lt;element name="Duration" type="{http://www.w3.org/2001/XMLSchema}short"/>
	 *                                       &lt;element name="KeyId" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *                                       &lt;element name="Hash" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *                                     &lt;/sequence>
	 *                                   &lt;/restriction>
	 *                                 &lt;/complexContent>
	 *                               &lt;/complexType>
	 *                             &lt;/element>
	 *                             &lt;element name="MainSubtitle" minOccurs="0">
	 *                               &lt;complexType>
	 *                                 &lt;complexContent>
	 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                                     &lt;sequence>
	 *                                       &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *                                       &lt;element name="EditRate" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *                                       &lt;element name="IntrinsicDuration" type="{http://www.w3.org/2001/XMLSchema}short"/>
	 *                                       &lt;element name="EntryPoint" type="{http://www.w3.org/2001/XMLSchema}byte"/>
	 *                                       &lt;element name="Duration" type="{http://www.w3.org/2001/XMLSchema}short"/>
	 *                                       &lt;element name="Hash" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *                                     &lt;/sequence>
	 *                                   &lt;/restriction>
	 *                                 &lt;/complexContent>
	 *                               &lt;/complexType>
	 *                             &lt;/element>
	 *                           &lt;/sequence>
	 *                         &lt;/restriction>
	 *                       &lt;/complexContent>
	 *                     &lt;/complexType>
	 *                   &lt;/element>
	 *                 &lt;/sequence>
	 *               &lt;/restriction>
	 *             &lt;/complexContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "reel" })
	public static class ReelList {

		@XmlElement(name = "Reel")
		protected List<CompositionPlaylist.ReelList.Reel> reel;

		/**
		 * Gets the value of the reel property.
		 * 
		 * <p>
		 * This accessor method returns a reference to the live list, not a
		 * snapshot. Therefore any modification you make to the returned list
		 * will be present inside the JAXB object. This is why there is not a
		 * <CODE>set</CODE> method for the reel property.
		 * 
		 * <p>
		 * For example, to add a new item, do as follows:
		 * 
		 * <pre>
		 * getReel().add(newItem);
		 * </pre>
		 * 
		 * 
		 * <p>
		 * Objects of the following type(s) are allowed in the list
		 * {@link CompositionPlaylist.ReelList.Reel }
		 * 
		 * 
		 */
		public List<CompositionPlaylist.ReelList.Reel> getReel() {
			if (reel == null) {
				reel = new ArrayList<CompositionPlaylist.ReelList.Reel>();
			}
			return this.reel;
		}

		/**
		 * <p>
		 * Java class for anonymous complex type.
		 * 
		 * <p>
		 * The following schema fragment specifies the expected content
		 * contained within this class.
		 * 
		 * <pre>
		 * &lt;complexType>
		 *   &lt;complexContent>
		 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *       &lt;sequence>
		 *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}string"/>
		 *         &lt;element name="AssetList">
		 *           &lt;complexType>
		 *             &lt;complexContent>
		 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *                 &lt;sequence>
		 *                   &lt;element name="MainPicture">
		 *                     &lt;complexType>
		 *                       &lt;complexContent>
		 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *                           &lt;sequence>
		 *                             &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}string"/>
		 *                             &lt;element name="EditRate" type="{http://www.w3.org/2001/XMLSchema}string"/>
		 *                             &lt;element name="IntrinsicDuration" type="{http://www.w3.org/2001/XMLSchema}short"/>
		 *                             &lt;element name="EntryPoint" type="{http://www.w3.org/2001/XMLSchema}short"/>
		 *                             &lt;element name="Duration" type="{http://www.w3.org/2001/XMLSchema}short"/>
		 *                             &lt;element name="KeyId" type="{http://www.w3.org/2001/XMLSchema}string"/>
		 *                             &lt;element name="Hash" type="{http://www.w3.org/2001/XMLSchema}string"/>
		 *                             &lt;element name="FrameRate" type="{http://www.w3.org/2001/XMLSchema}string"/>
		 *                             &lt;element name="ScreenAspectRatio" type="{http://www.w3.org/2001/XMLSchema}float"/>
		 *                           &lt;/sequence>
		 *                         &lt;/restriction>
		 *                       &lt;/complexContent>
		 *                     &lt;/complexType>
		 *                   &lt;/element>
		 *                   &lt;element name="MainSound">
		 *                     &lt;complexType>
		 *                       &lt;complexContent>
		 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *                           &lt;sequence>
		 *                             &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}string"/>
		 *                             &lt;element name="EditRate" type="{http://www.w3.org/2001/XMLSchema}string"/>
		 *                             &lt;element name="IntrinsicDuration" type="{http://www.w3.org/2001/XMLSchema}short"/>
		 *                             &lt;element name="EntryPoint" type="{http://www.w3.org/2001/XMLSchema}short"/>
		 *                             &lt;element name="Duration" type="{http://www.w3.org/2001/XMLSchema}short"/>
		 *                             &lt;element name="KeyId" type="{http://www.w3.org/2001/XMLSchema}string"/>
		 *                             &lt;element name="Hash" type="{http://www.w3.org/2001/XMLSchema}string"/>
		 *                           &lt;/sequence>
		 *                         &lt;/restriction>
		 *                       &lt;/complexContent>
		 *                     &lt;/complexType>
		 *                   &lt;/element>
		 *                   &lt;element name="MainSubtitle" minOccurs="0">
		 *                     &lt;complexType>
		 *                       &lt;complexContent>
		 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *                           &lt;sequence>
		 *                             &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}string"/>
		 *                             &lt;element name="EditRate" type="{http://www.w3.org/2001/XMLSchema}string"/>
		 *                             &lt;element name="IntrinsicDuration" type="{http://www.w3.org/2001/XMLSchema}short"/>
		 *                             &lt;element name="EntryPoint" type="{http://www.w3.org/2001/XMLSchema}byte"/>
		 *                             &lt;element name="Duration" type="{http://www.w3.org/2001/XMLSchema}short"/>
		 *                             &lt;element name="Hash" type="{http://www.w3.org/2001/XMLSchema}string"/>
		 *                           &lt;/sequence>
		 *                         &lt;/restriction>
		 *                       &lt;/complexContent>
		 *                     &lt;/complexType>
		 *                   &lt;/element>
		 *                 &lt;/sequence>
		 *               &lt;/restriction>
		 *             &lt;/complexContent>
		 *           &lt;/complexType>
		 *         &lt;/element>
		 *       &lt;/sequence>
		 *     &lt;/restriction>
		 *   &lt;/complexContent>
		 * &lt;/complexType>
		 * </pre>
		 * 
		 * 
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = { "id", "assetList" })
		public static class Reel {

			@XmlElement(name = "Id", required = true)
			protected String id;
			@XmlElement(name = "AssetList", required = true)
			protected CompositionPlaylist.ReelList.Reel.AssetList assetList;

			/**
			 * Gets the value of the id property.
			 * 
			 * @return possible object is {@link String }
			 * 
			 */
			public String getId() {
				return id;
			}

			/**
			 * Sets the value of the id property.
			 * 
			 * @param value
			 *            allowed object is {@link String }
			 * 
			 */
			public void setId(String value) {
				this.id = value;
			}

			/**
			 * Gets the value of the assetList property.
			 * 
			 * @return possible object is
			 *         {@link CompositionPlaylist.ReelList.Reel.AssetList }
			 * 
			 */
			public CompositionPlaylist.ReelList.Reel.AssetList getAssetList() {
				return assetList;
			}

			/**
			 * Sets the value of the assetList property.
			 * 
			 * @param value
			 *            allowed object is
			 *            {@link CompositionPlaylist.ReelList.Reel.AssetList }
			 * 
			 */
			public void setAssetList(CompositionPlaylist.ReelList.Reel.AssetList value) {
				this.assetList = value;
			}

			/**
			 * <p>
			 * Java class for anonymous complex type.
			 * 
			 * <p>
			 * The following schema fragment specifies the expected content
			 * contained within this class.
			 * 
			 * <pre>
			 * &lt;complexType>
			 *   &lt;complexContent>
			 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
			 *       &lt;sequence>
			 *         &lt;element name="MainPicture">
			 *           &lt;complexType>
			 *             &lt;complexContent>
			 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
			 *                 &lt;sequence>
			 *                   &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}string"/>
			 *                   &lt;element name="EditRate" type="{http://www.w3.org/2001/XMLSchema}string"/>
			 *                   &lt;element name="IntrinsicDuration" type="{http://www.w3.org/2001/XMLSchema}short"/>
			 *                   &lt;element name="EntryPoint" type="{http://www.w3.org/2001/XMLSchema}short"/>
			 *                   &lt;element name="Duration" type="{http://www.w3.org/2001/XMLSchema}short"/>
			 *                   &lt;element name="KeyId" type="{http://www.w3.org/2001/XMLSchema}string"/>
			 *                   &lt;element name="Hash" type="{http://www.w3.org/2001/XMLSchema}string"/>
			 *                   &lt;element name="FrameRate" type="{http://www.w3.org/2001/XMLSchema}string"/>
			 *                   &lt;element name="ScreenAspectRatio" type="{http://www.w3.org/2001/XMLSchema}float"/>
			 *                 &lt;/sequence>
			 *               &lt;/restriction>
			 *             &lt;/complexContent>
			 *           &lt;/complexType>
			 *         &lt;/element>
			 *         &lt;element name="MainSound">
			 *           &lt;complexType>
			 *             &lt;complexContent>
			 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
			 *                 &lt;sequence>
			 *                   &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}string"/>
			 *                   &lt;element name="EditRate" type="{http://www.w3.org/2001/XMLSchema}string"/>
			 *                   &lt;element name="IntrinsicDuration" type="{http://www.w3.org/2001/XMLSchema}short"/>
			 *                   &lt;element name="EntryPoint" type="{http://www.w3.org/2001/XMLSchema}short"/>
			 *                   &lt;element name="Duration" type="{http://www.w3.org/2001/XMLSchema}short"/>
			 *                   &lt;element name="KeyId" type="{http://www.w3.org/2001/XMLSchema}string"/>
			 *                   &lt;element name="Hash" type="{http://www.w3.org/2001/XMLSchema}string"/>
			 *                 &lt;/sequence>
			 *               &lt;/restriction>
			 *             &lt;/complexContent>
			 *           &lt;/complexType>
			 *         &lt;/element>
			 *         &lt;element name="MainSubtitle" minOccurs="0">
			 *           &lt;complexType>
			 *             &lt;complexContent>
			 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
			 *                 &lt;sequence>
			 *                   &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}string"/>
			 *                   &lt;element name="EditRate" type="{http://www.w3.org/2001/XMLSchema}string"/>
			 *                   &lt;element name="IntrinsicDuration" type="{http://www.w3.org/2001/XMLSchema}short"/>
			 *                   &lt;element name="EntryPoint" type="{http://www.w3.org/2001/XMLSchema}byte"/>
			 *                   &lt;element name="Duration" type="{http://www.w3.org/2001/XMLSchema}short"/>
			 *                   &lt;element name="Hash" type="{http://www.w3.org/2001/XMLSchema}string"/>
			 *                 &lt;/sequence>
			 *               &lt;/restriction>
			 *             &lt;/complexContent>
			 *           &lt;/complexType>
			 *         &lt;/element>
			 *       &lt;/sequence>
			 *     &lt;/restriction>
			 *   &lt;/complexContent>
			 * &lt;/complexType>
			 * </pre>
			 * 
			 * 
			 */
			@XmlAccessorType(XmlAccessType.FIELD)
			@XmlType(name = "", propOrder = { "mainPicture", "mainSound", "mainSubtitle" })
			public static class AssetList {

				@XmlElement(name = "MainPicture", required = true)
				protected CompositionPlaylist.ReelList.Reel.AssetList.MainPicture mainPicture;
				@XmlElement(name = "MainSound", required = true)
				protected CompositionPlaylist.ReelList.Reel.AssetList.MainSound mainSound;
				@XmlElement(name = "MainSubtitle")
				protected CompositionPlaylist.ReelList.Reel.AssetList.MainSubtitle mainSubtitle;

				/**
				 * Gets the value of the mainPicture property.
				 * 
				 * @return possible object is
				 *         {@link CompositionPlaylist.ReelList.Reel.AssetList.MainPicture }
				 * 
				 */
				public CompositionPlaylist.ReelList.Reel.AssetList.MainPicture getMainPicture() {
					return mainPicture;
				}

				/**
				 * Sets the value of the mainPicture property.
				 * 
				 * @param value
				 *            allowed object is
				 *            {@link CompositionPlaylist.ReelList.Reel.AssetList.MainPicture }
				 * 
				 */
				public void setMainPicture(
				        CompositionPlaylist.ReelList.Reel.AssetList.MainPicture value) {
					this.mainPicture = value;
				}

				/**
				 * Gets the value of the mainSound property.
				 * 
				 * @return possible object is
				 *         {@link CompositionPlaylist.ReelList.Reel.AssetList.MainSound }
				 * 
				 */
				public CompositionPlaylist.ReelList.Reel.AssetList.MainSound getMainSound() {
					return mainSound;
				}

				/**
				 * Sets the value of the mainSound property.
				 * 
				 * @param value
				 *            allowed object is
				 *            {@link CompositionPlaylist.ReelList.Reel.AssetList.MainSound }
				 * 
				 */
				public void setMainSound(CompositionPlaylist.ReelList.Reel.AssetList.MainSound value) {
					this.mainSound = value;
				}

				/**
				 * Gets the value of the mainSubtitle property.
				 * 
				 * @return possible object is
				 *         {@link CompositionPlaylist.ReelList.Reel.AssetList.MainSubtitle }
				 * 
				 */
				public CompositionPlaylist.ReelList.Reel.AssetList.MainSubtitle getMainSubtitle() {
					return mainSubtitle;
				}

				/**
				 * Sets the value of the mainSubtitle property.
				 * 
				 * @param value
				 *            allowed object is
				 *            {@link CompositionPlaylist.ReelList.Reel.AssetList.MainSubtitle }
				 * 
				 */
				public void setMainSubtitle(
				        CompositionPlaylist.ReelList.Reel.AssetList.MainSubtitle value) {
					this.mainSubtitle = value;
				}

				/**
				 * <p>
				 * Java class for anonymous complex type.
				 * 
				 * <p>
				 * The following schema fragment specifies the expected content
				 * contained within this class.
				 * 
				 * <pre>
				 * &lt;complexType>
				 *   &lt;complexContent>
				 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
				 *       &lt;sequence>
				 *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}string"/>
				 *         &lt;element name="EditRate" type="{http://www.w3.org/2001/XMLSchema}string"/>
				 *         &lt;element name="IntrinsicDuration" type="{http://www.w3.org/2001/XMLSchema}short"/>
				 *         &lt;element name="EntryPoint" type="{http://www.w3.org/2001/XMLSchema}short"/>
				 *         &lt;element name="Duration" type="{http://www.w3.org/2001/XMLSchema}short"/>
				 *         &lt;element name="KeyId" type="{http://www.w3.org/2001/XMLSchema}string"/>
				 *         &lt;element name="Hash" type="{http://www.w3.org/2001/XMLSchema}string"/>
				 *         &lt;element name="FrameRate" type="{http://www.w3.org/2001/XMLSchema}string"/>
				 *         &lt;element name="ScreenAspectRatio" type="{http://www.w3.org/2001/XMLSchema}float"/>
				 *       &lt;/sequence>
				 *     &lt;/restriction>
				 *   &lt;/complexContent>
				 * &lt;/complexType>
				 * </pre>
				 * 
				 * 
				 */
				@XmlAccessorType(XmlAccessType.FIELD)
				@XmlType(name = "", propOrder = { "id", "editRate", "intrinsicDuration",
				        "entryPoint", "duration", "keyId", "hash", "frameRate", "screenAspectRatio" })
				public static class MainPicture {

					@XmlElement(name = "Id", required = true)
					protected String id;
					@XmlElement(name = "EditRate", required = true)
					protected String editRate;
					@XmlElement(name = "IntrinsicDuration")
					protected short intrinsicDuration;
					@XmlElement(name = "EntryPoint")
					protected short entryPoint;
					@XmlElement(name = "Duration")
					protected short duration;
					@XmlElement(name = "KeyId", required = true)
					protected String keyId;
					@XmlElement(name = "Hash", required = true)
					protected String hash;
					@XmlElement(name = "FrameRate", required = true)
					protected String frameRate;
					@XmlElement(name = "ScreenAspectRatio")
					protected float screenAspectRatio;

					/**
					 * Gets the value of the id property.
					 * 
					 * @return possible object is {@link String }
					 * 
					 */
					public String getId() {
						return id;
					}

					/**
					 * Sets the value of the id property.
					 * 
					 * @param value
					 *            allowed object is {@link String }
					 * 
					 */
					public void setId(String value) {
						this.id = value;
					}

					/**
					 * Gets the value of the editRate property.
					 * 
					 * @return possible object is {@link String }
					 * 
					 */
					public String getEditRate() {
						return editRate;
					}

					/**
					 * Sets the value of the editRate property.
					 * 
					 * @param value
					 *            allowed object is {@link String }
					 * 
					 */
					public void setEditRate(String value) {
						this.editRate = value;
					}

					/**
					 * Gets the value of the intrinsicDuration property.
					 * 
					 */
					public short getIntrinsicDuration() {
						return intrinsicDuration;
					}

					/**
					 * Sets the value of the intrinsicDuration property.
					 * 
					 */
					public void setIntrinsicDuration(short value) {
						this.intrinsicDuration = value;
					}

					/**
					 * Gets the value of the entryPoint property.
					 * 
					 */
					public short getEntryPoint() {
						return entryPoint;
					}

					/**
					 * Sets the value of the entryPoint property.
					 * 
					 */
					public void setEntryPoint(short value) {
						this.entryPoint = value;
					}

					/**
					 * Gets the value of the duration property.
					 * 
					 */
					public short getDuration() {
						return duration;
					}

					/**
					 * Sets the value of the duration property.
					 * 
					 */
					public void setDuration(short value) {
						this.duration = value;
					}

					/**
					 * Gets the value of the keyId property.
					 * 
					 * @return possible object is {@link String }
					 * 
					 */
					public String getKeyId() {
						return keyId;
					}

					/**
					 * Sets the value of the keyId property.
					 * 
					 * @param value
					 *            allowed object is {@link String }
					 * 
					 */
					public void setKeyId(String value) {
						this.keyId = value;
					}

					/**
					 * Gets the value of the hash property.
					 * 
					 * @return possible object is {@link String }
					 * 
					 */
					public String getHash() {
						return hash;
					}

					/**
					 * Sets the value of the hash property.
					 * 
					 * @param value
					 *            allowed object is {@link String }
					 * 
					 */
					public void setHash(String value) {
						this.hash = value;
					}

					/**
					 * Gets the value of the frameRate property.
					 * 
					 * @return possible object is {@link String }
					 * 
					 */
					public String getFrameRate() {
						return frameRate;
					}

					/**
					 * Sets the value of the frameRate property.
					 * 
					 * @param value
					 *            allowed object is {@link String }
					 * 
					 */
					public void setFrameRate(String value) {
						this.frameRate = value;
					}

					/**
					 * Gets the value of the screenAspectRatio property.
					 * 
					 */
					public float getScreenAspectRatio() {
						return screenAspectRatio;
					}

					/**
					 * Sets the value of the screenAspectRatio property.
					 * 
					 */
					public void setScreenAspectRatio(float value) {
						this.screenAspectRatio = value;
					}

				}

				/**
				 * <p>
				 * Java class for anonymous complex type.
				 * 
				 * <p>
				 * The following schema fragment specifies the expected content
				 * contained within this class.
				 * 
				 * <pre>
				 * &lt;complexType>
				 *   &lt;complexContent>
				 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
				 *       &lt;sequence>
				 *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}string"/>
				 *         &lt;element name="EditRate" type="{http://www.w3.org/2001/XMLSchema}string"/>
				 *         &lt;element name="IntrinsicDuration" type="{http://www.w3.org/2001/XMLSchema}short"/>
				 *         &lt;element name="EntryPoint" type="{http://www.w3.org/2001/XMLSchema}short"/>
				 *         &lt;element name="Duration" type="{http://www.w3.org/2001/XMLSchema}short"/>
				 *         &lt;element name="KeyId" type="{http://www.w3.org/2001/XMLSchema}string"/>
				 *         &lt;element name="Hash" type="{http://www.w3.org/2001/XMLSchema}string"/>
				 *       &lt;/sequence>
				 *     &lt;/restriction>
				 *   &lt;/complexContent>
				 * &lt;/complexType>
				 * </pre>
				 * 
				 * 
				 */
				@XmlAccessorType(XmlAccessType.FIELD)
				@XmlType(name = "", propOrder = { "id", "editRate", "intrinsicDuration",
				        "entryPoint", "duration", "keyId", "hash" })
				public static class MainSound {

					@XmlElement(name = "Id", required = true)
					protected String id;
					@XmlElement(name = "EditRate", required = true)
					protected String editRate;
					@XmlElement(name = "IntrinsicDuration")
					protected short intrinsicDuration;
					@XmlElement(name = "EntryPoint")
					protected short entryPoint;
					@XmlElement(name = "Duration")
					protected short duration;
					@XmlElement(name = "KeyId", required = true)
					protected String keyId;
					@XmlElement(name = "Hash", required = true)
					protected String hash;

					/**
					 * Gets the value of the id property.
					 * 
					 * @return possible object is {@link String }
					 * 
					 */
					public String getId() {
						return id;
					}

					/**
					 * Sets the value of the id property.
					 * 
					 * @param value
					 *            allowed object is {@link String }
					 * 
					 */
					public void setId(String value) {
						this.id = value;
					}

					/**
					 * Gets the value of the editRate property.
					 * 
					 * @return possible object is {@link String }
					 * 
					 */
					public String getEditRate() {
						return editRate;
					}

					/**
					 * Sets the value of the editRate property.
					 * 
					 * @param value
					 *            allowed object is {@link String }
					 * 
					 */
					public void setEditRate(String value) {
						this.editRate = value;
					}

					/**
					 * Gets the value of the intrinsicDuration property.
					 * 
					 */
					public short getIntrinsicDuration() {
						return intrinsicDuration;
					}

					/**
					 * Sets the value of the intrinsicDuration property.
					 * 
					 */
					public void setIntrinsicDuration(short value) {
						this.intrinsicDuration = value;
					}

					/**
					 * Gets the value of the entryPoint property.
					 * 
					 */
					public short getEntryPoint() {
						return entryPoint;
					}

					/**
					 * Sets the value of the entryPoint property.
					 * 
					 */
					public void setEntryPoint(short value) {
						this.entryPoint = value;
					}

					/**
					 * Gets the value of the duration property.
					 * 
					 */
					public short getDuration() {
						return duration;
					}

					/**
					 * Sets the value of the duration property.
					 * 
					 */
					public void setDuration(short value) {
						this.duration = value;
					}

					/**
					 * Gets the value of the keyId property.
					 * 
					 * @return possible object is {@link String }
					 * 
					 */
					public String getKeyId() {
						return keyId;
					}

					/**
					 * Sets the value of the keyId property.
					 * 
					 * @param value
					 *            allowed object is {@link String }
					 * 
					 */
					public void setKeyId(String value) {
						this.keyId = value;
					}

					/**
					 * Gets the value of the hash property.
					 * 
					 * @return possible object is {@link String }
					 * 
					 */
					public String getHash() {
						return hash;
					}

					/**
					 * Sets the value of the hash property.
					 * 
					 * @param value
					 *            allowed object is {@link String }
					 * 
					 */
					public void setHash(String value) {
						this.hash = value;
					}

				}

				/**
				 * <p>
				 * Java class for anonymous complex type.
				 * 
				 * <p>
				 * The following schema fragment specifies the expected content
				 * contained within this class.
				 * 
				 * <pre>
				 * &lt;complexType>
				 *   &lt;complexContent>
				 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
				 *       &lt;sequence>
				 *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}string"/>
				 *         &lt;element name="EditRate" type="{http://www.w3.org/2001/XMLSchema}string"/>
				 *         &lt;element name="IntrinsicDuration" type="{http://www.w3.org/2001/XMLSchema}short"/>
				 *         &lt;element name="EntryPoint" type="{http://www.w3.org/2001/XMLSchema}byte"/>
				 *         &lt;element name="Duration" type="{http://www.w3.org/2001/XMLSchema}short"/>
				 *         &lt;element name="Hash" type="{http://www.w3.org/2001/XMLSchema}string"/>
				 *       &lt;/sequence>
				 *     &lt;/restriction>
				 *   &lt;/complexContent>
				 * &lt;/complexType>
				 * </pre>
				 * 
				 * 
				 */
				@XmlAccessorType(XmlAccessType.FIELD)
				@XmlType(name = "", propOrder = { "id", "editRate", "intrinsicDuration",
				        "entryPoint", "duration", "hash" })
				public static class MainSubtitle {

					@XmlElement(name = "Id", required = true)
					protected String id;
					@XmlElement(name = "EditRate", required = true)
					protected String editRate;
					@XmlElement(name = "IntrinsicDuration")
					protected short intrinsicDuration;
					@XmlElement(name = "EntryPoint")
					protected byte entryPoint;
					@XmlElement(name = "Duration")
					protected short duration;
					@XmlElement(name = "Hash", required = true)
					protected String hash;

					/**
					 * Gets the value of the id property.
					 * 
					 * @return possible object is {@link String }
					 * 
					 */
					public String getId() {
						return id;
					}

					/**
					 * Sets the value of the id property.
					 * 
					 * @param value
					 *            allowed object is {@link String }
					 * 
					 */
					public void setId(String value) {
						this.id = value;
					}

					/**
					 * Gets the value of the editRate property.
					 * 
					 * @return possible object is {@link String }
					 * 
					 */
					public String getEditRate() {
						return editRate;
					}

					/**
					 * Sets the value of the editRate property.
					 * 
					 * @param value
					 *            allowed object is {@link String }
					 * 
					 */
					public void setEditRate(String value) {
						this.editRate = value;
					}

					/**
					 * Gets the value of the intrinsicDuration property.
					 * 
					 */
					public short getIntrinsicDuration() {
						return intrinsicDuration;
					}

					/**
					 * Sets the value of the intrinsicDuration property.
					 * 
					 */
					public void setIntrinsicDuration(short value) {
						this.intrinsicDuration = value;
					}

					/**
					 * Gets the value of the entryPoint property.
					 * 
					 */
					public byte getEntryPoint() {
						return entryPoint;
					}

					/**
					 * Sets the value of the entryPoint property.
					 * 
					 */
					public void setEntryPoint(byte value) {
						this.entryPoint = value;
					}

					/**
					 * Gets the value of the duration property.
					 * 
					 */
					public short getDuration() {
						return duration;
					}

					/**
					 * Sets the value of the duration property.
					 * 
					 */
					public void setDuration(short value) {
						this.duration = value;
					}

					/**
					 * Gets the value of the hash property.
					 * 
					 * @return possible object is {@link String }
					 * 
					 */
					public String getHash() {
						return hash;
					}

					/**
					 * Sets the value of the hash property.
					 * 
					 * @param value
					 *            allowed object is {@link String }
					 * 
					 */
					public void setHash(String value) {
						this.hash = value;
					}

				}

			}

		}

	}

	private static final Logger logger = Logger.getLogger(CompositionPlaylist.class);

	/**
	 * Returns the unmarshalled CPL instance from the file
	 * 
	 * @param cplPath
	 * @return
	 */
	public static CompositionPlaylist fromFile(String cplPath) {
		InputStream is = null;
		try {
			is = new FileInputStream(cplPath);
			XMLStreamReader xsr = XMLInputFactory.newFactory().createXMLStreamReader(is);
			XMLReaderWithoutNamespace xr = new XMLReaderWithoutNamespace(xsr);
			return (CompositionPlaylist) JAXBContext.newInstance(CompositionPlaylist.class)
			        .createUnmarshaller().unmarshal(xr);
		} catch (RuntimeException e) {
			throw e;
		} catch (Exception e) {
			logger.error(cplPath + " is not a cpl file");
		} finally {
			if (is != null) {
				try {
					is.close();
				} catch (IOException e) {
					logger.error(e);
				}
			}
		}
		return null;
	}

}
