//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.03 at 05:38:02 PM CEST 
//

//@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.digicine.com/PROTO-ASDCP-CPL-20040511#", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.cineapps.acs_ftp.model;

