
package com.dolby.dcinema.ws.smi.v1;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.1
 * 2015-07-09T17:41:03.985+02:00
 * Generated source version: 3.1.1
 */

@WebFault(name = "fault", targetNamespace = "http://www.dolby.com/dcinema/ws/smi/v1_0")
public class Fault extends Exception {
    
    private com.dolby.dcinema.ws.smi.v1.schemas.fault.Fault fault;

    public Fault() {
        super();
    }
    
    public Fault(String message) {
        super(message);
    }
    
    public Fault(String message, Throwable cause) {
        super(message, cause);
    }

    public Fault(String message, com.dolby.dcinema.ws.smi.v1.schemas.fault.Fault fault) {
        super(message);
        this.fault = fault;
    }

    public Fault(String message, com.dolby.dcinema.ws.smi.v1.schemas.fault.Fault fault, Throwable cause) {
        super(message, cause);
        this.fault = fault;
    }

    public com.dolby.dcinema.ws.smi.v1.schemas.fault.Fault getFaultInfo() {
        return this.fault;
    }
}
