package com.dolby.dcinema.ws.smi.v1;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.1
 * 2015-07-09T17:41:04.178+02:00
 * Generated source version: 3.1.1
 * 
 */
@WebServiceClient(name = "ShowManagement_v1_0", 
                  wsdlLocation = "/dolby-smi/ShowManagement.wsdl",
                  targetNamespace = "http://www.dolby.com/dcinema/ws/smi/v1") 
public class ShowManagementV10 extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.dolby.com/dcinema/ws/smi/v1", "ShowManagement_v1_0");
    public final static QName ShowManagementServiceV10 = new QName("http://www.dolby.com/dcinema/ws/smi/v1", "ShowManagementService_v1_0");
    static {
        URL url = ShowManagementV10.class.getResource("/dolby-smi/ShowManagement.wsdl");
        if (url == null) {
            url = ShowManagementV10.class.getClassLoader().getResource("/dolby-smi/ShowManagement.wsdl");
        } 
        if (url == null) {
            java.util.logging.Logger.getLogger(ShowManagementV10.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "/dolby-smi/ShowManagement.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public ShowManagementV10(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ShowManagementV10(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ShowManagementV10() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public ShowManagementV10(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ShowManagementV10(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ShowManagementV10(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns ShowManagementServiceV10
     */
    @WebEndpoint(name = "ShowManagementService_v1_0")
    public ShowManagementServiceV10 getShowManagementServiceV10() {
        return super.getPort(ShowManagementServiceV10, ShowManagementServiceV10.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ShowManagementServiceV10
     */
    @WebEndpoint(name = "ShowManagementService_v1_0")
    public ShowManagementServiceV10 getShowManagementServiceV10(WebServiceFeature... features) {
        return super.getPort(ShowManagementServiceV10, ShowManagementServiceV10.class, features);
    }

}
